let maindata = [
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 2,
    Title: "Christmas",
    CategoryName: "celebration",
    Category: 1,
    Date: "25 Dec 2021",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy X mas",
    Text: "Wish you a Happy X mas",
  },
  {
    Id: 3,
    Title: "Christmas",
    CategoryName: "celebration",
    Category: 1,
    Date: "25 Dec 2021",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
  },
  {
    Id: 4,
    Title: "Test",
    CategoryName: "celebration",
    Category: 1,
    Date: "25 Dec 2021",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
  {
    Id: 1,
    Title: "New Year",
    CategoryName: "celebration",
    Category: 1,
    Date: "01 Jan 2022",
    Repeat: true,
    RepeatIntervalName: "Yearly",
    RepeatInterval: 1,
    Heading: "Happy New Year",
    Text: "Wish you a Happy New Year",
  },
];

export default maindata;
